spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB-URL}
    username: ${DB-USERNAME}
    password: ${DB-PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  error:
    whitelabel:
      enabled: false

encrypt:
  salt: ${ENCRYPT-SALT}

image:
  url: "http://localhost:8080/api/v1/images/"