# JPA Query Production용 설정
spring:
  jpa:
    properties:
      hibernate:
        format_sql: false #To beautify or pretty print the SQL
        show_sql: false #show sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB-URL}
    username: ${DB-USERNAME}
    password: ${DB-PASS}

logging.level.org.springframework: INFO