name: Jacoco Coverage Test

on:
  pull_request:
    branches:
      ["main"]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Add application test properties secrets
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/test/resources/application-test.yaml
        env:
          encrypt.salt: ${{ secrets.ENCRYPT_SALT }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew build --info test

      - name: Jacoco Test Coverage Report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 'Jacoco Test Coverage Report'
          paths: ${{ github.workspace }}/build/jacoco/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80